security:
  oauth2:
    client:
      clientId: ${fbAppId}
      clientSecret: ${fbAppSecret}
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

my:
  #picBaseUrl: https://pagypics.kari.iki.fi/
  picBaseUrl: https://storage.googleapis.com/pagypics.kari.iki.fi/